server {
    # Listen on port 8080 as expected by Google Cloud Run
    listen 8080;

    # Where the static files are stored
    root /usr/share/nginx/html;
    index index.html;

    # Route all requests to index.html for React SPA router
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Browser caching for static assets
    location ~* \.(?:css|js|jpg|svg)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}
